/*
  DeutschWelt

  IMPORTANT ARCHITECTURE:
  -----------------------
  GitHub = website code
  Supabase = ALL learning content

  For normal future additions, you do NOT edit this file.
  Add the content in Supabase Table Editor instead.
*/

// =====================================================
// 1. SUPABASE CONNECTION
// =====================================================

const SUPABASE_URL = "https://llxcyabptsbdtsdhkzkc.supabase.co";

const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxseGN5YWJwdHNiZHRzZGhremtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5NjE3NTAsImV4cCI6MjEwNDUzNzc1MH0.cYvadDwigcXKlmbtN7s7jAVJCyXOO82uU3CC3Dz52vg";

const SUPABASE_CDN =
  "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";

let db = null;

const page =
  document.body.dataset.page || "";


// =====================================================
// 2. SMALL HELPER FUNCTIONS
// =====================================================

function esc(value = "") {

  return String(value).replace(
    /[&<>"']/g,

    function (character) {

      return {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;"
      }[character];

    }
  );
}


function listify(value) {

  if (!value) {
    return [];
  }

  if (Array.isArray(value)) {
    return value;
  }

  try {
    return JSON.parse(value);
  } catch (error) {
    return String(value)
      .split(/\n+/)
      .map(item => item.trim())
      .filter(Boolean);
  }
}


// =====================================================
// 3. CONNECT TO SUPABASE
// =====================================================

async function connectSupabase() {

  /*
    Do nothing until you enter your credentials.
  */

  if (
    !SUPABASE_URL ||
    SUPABASE_URL.includes("PASTE_") ||

    !SUPABASE_ANON_KEY ||
    SUPABASE_ANON_KEY.includes("PASTE_")
  ) {

    console.warn(
      "Supabase URL and key have not been added yet."
    );

    return false;
  }


  /*
    Load Supabase JavaScript library.
  */

  if (!window.supabase) {

    await new Promise(
      function (resolve, reject) {

        const script =
          document.createElement("script");

        script.src =
          SUPABASE_CDN;

        script.onload = resolve;

        script.onerror = reject;

        document.head.appendChild(script);

      }
    ).catch(
      function (error) {

        console.error(
          "Could not load Supabase library.",
          error
        );

      }
    );

  }


  if (!window.supabase) {

    return false;

  }


  /*
    Create Supabase client.
  */

  db =
    window.supabase.createClient(
      SUPABASE_URL,
      SUPABASE_ANON_KEY
    );


  return true;

}


// =====================================================
// 4. GET DATA FROM SUPABASE
// =====================================================

async function getRows(
  table,
  options = {}
) {

  if (!db) {

    return {
      data: null,
      error:
        new Error("Supabase is not connected.")
    };

  }


  let query =
    db
      .from(table)
      .select(options.select || "*");


  /*
    Equality filters
  */

  if (options.eq) {

    for (
      const [column, value]
      of Object.entries(options.eq)
    ) {

      query =
        query.eq(column, value);

    }

  }


  /*
    Sorting
  */

  if (options.order) {

    query =
      query.order(
        options.order,
        {
          ascending: true
        }
      );

  }


  return await query;

}


// =====================================================
// 5. FALLBACK LEVELS
// =====================================================

/*
  These are only used when Supabase is not connected.

  Once your Supabase database works,
  the website uses Supabase data.
*/

const fallbackLevels = [

  {
    level: "A1",

    title:
      "Dein erster Schritt",

    tagline:
      "Von Hallo zu deinen ersten Sätzen.",

    goal:
      "Einfache Alltagssituationen verstehen, sich vorstellen und kurze Sätze benutzen.",

    description:
      "Grundlagen für erste Kontakte und einfache Alltagssituationen.",

    theme_count: 14,

    grammar_count: 18
  },


  {
    level: "A2",

    title:
      "Mehr verstehen. Mehr sagen.",

    tagline:
      "Dein Deutsch wird sicherer und vielseitiger.",

    goal:
      "Vertraute Alltagssituationen selbstständiger bewältigen und über Erfahrungen und Pläne sprechen.",

    description:
      "Über vertraute Themen sprechen und mehr Zusammenhänge verstehen.",

    theme_count: 14,

    grammar_count: 18
  },


  {
    level: "B1",

    title:
      "Mit Deutsch selbstständig durch die Welt",

    tagline:
      "Zusammenhängend sprechen, schreiben und deine Meinung ausdrücken.",

    goal:
      "Klare Standardsprache verstehen und sich zu vertrauten Themen zusammenhängend äußern.",

    description:
      "Selbstständiger kommunizieren und Gedanken begründen.",

    theme_count: 15,

    grammar_count: 20
  }

];


// =====================================================
// 6. HEADER
// =====================================================

function renderHeader() {

  const header =
    document.getElementById(
      "site-header"
    );

  if (!header) {
    return;
  }


  header.innerHTML = `

    <header class="site-header">

      <div class="shell navbar">

        <a
          class="brand"
          href="index.html"
        >

          <span class="brand-mark">
            D
          </span>

          <span>
            DeutschWelt
          </span>

        </a>


        <button
          class="menu-toggle"
          id="menuToggle"
          aria-expanded="false"
          aria-label="Menü öffnen"
        >
          ☰
        </button>


        <nav
          class="nav-links"
          id="mainNav"
        >

          <a
            class="${page === "home" ? "active" : ""}"
            href="index.html"
          >
            Startseite
          </a>


          <a
            class="${page === "learn" || page === "level" ? "active" : ""}"
            href="lernen.html"
          >
            Lernwelten
          </a>


          <a
            class="${page === "vocabulary" ? "active" : ""}"
            href="wortschatz.html"
          >
            Wortschatz
          </a>


          <a
            class="${page === "grammar" ? "active" : ""}"
            href="grammatik.html"
          >
            Grammatik
          </a>

        </nav>

      </div>

    </header>

  `;


  /*
    Mobile menu
  */

  const menuButton =
    document.getElementById(
      "menuToggle"
    );

  const navigation =
    document.getElementById(
      "mainNav"
    );


  if (
    menuButton &&
    navigation
  ) {

    menuButton.onclick =
      function () {

        const open =
          navigation.classList.toggle(
            "open"
          );


        menuButton.setAttribute(
          "aria-expanded",
          String(open)
        );

      };

  }

}


// =====================================================
// 7. FOOTER
// =====================================================

function renderFooter() {

  const footer =
    document.getElementById(
      "site-footer"
    );

  if (!footer) {
    return;
  }


  footer.innerHTML = `

    <footer class="site-footer">

      <div class="shell footer-row">

        <div>

          <div class="footer-brand">
            DeutschWelt
          </div>

          <p>
            Deutsch lernen.
            Verstehen.
            Wiederholen.
          </p>

        </div>


        <div>
          © ${new Date().getFullYear()}
          DeutschWelt
        </div>

      </div>

    </footer>

  `;

}


// =====================================================
// 8. GET LEVELS
// =====================================================

async function getLevels() {

  const result =
    await getRows(
      "levels",
      {
        order: "sort_order"
      }
    );


  if (
    !result.error &&
    result.data &&
    result.data.length
  ) {

    return result.data;

  }


  return fallbackLevels;

}


// =====================================================
// 9. LEVEL CARD
// =====================================================

function createLevelCard(
  level
) {

  const cssClass =
    String(
      level.level || ""
    ).toLowerCase();


  return `

    <article
      class="level-card ${cssClass}"
    >

      <span class="level-badge">
        ${esc(level.level)}
      </span>


      <h3>
        ${esc(level.title)}
      </h3>


      <p>
        ${esc(
          level.description ||
          level.tagline ||
          ""
        )}
      </p>


      <ul>

        <li>
          ${esc(
            level.theme_count ?? 0
          )}
          Themen
        </li>

        <li>
          ${esc(
            level.grammar_count ?? 0
          )}
          Grammatikthemen
        </li>

        <li>
          Lesen & wiederholen
        </li>

      </ul>


      <a
        class="card-arrow"
        href="${esc(
          String(level.level).toLowerCase()
        )}.html"
      >
        Niveau entdecken →
      </a>

    </article>

  `;

}


// =====================================================
// 10. HOME / LERNWELTEN
// =====================================================

async function renderLevelCards(
  containerId
) {

  const container =
    document.getElementById(
      containerId
    );

  if (!container) {
    return;
  }


  container.innerHTML = `

    <div class="loading">
      Lernwelten werden geladen …
    </div>

  `;


  const levels =
    await getLevels();


  container.innerHTML =
    levels
      .map(createLevelCard)
      .join("");

}


// =====================================================
// 11. LEVEL PAGE
// =====================================================

async function renderLevelPage(
  levelName
) {

  const intro =
    document.getElementById(
      "level-intro"
    );

  const topics =
    document.getElementById(
      "level-topics"
    );

  const grammar =
    document.getElementById(
      "level-grammar"
    );


  if (
    !intro ||
    !topics ||
    !grammar
  ) {
    return;
  }


  /*
    Temporary fallback introduction
  */

  const fallback =
    fallbackLevels.find(
      level =>
        level.level === levelName
    ) || {

      title: levelName,

      tagline: "",

      goal: ""

    };


  intro.innerHTML = `

    <div class="level-intro">

      <div>

        <span class="eyebrow">
          ${esc(levelName)}
        </span>

        <h1>
          ${esc(fallback.title)}
        </h1>

        <p>
          ${esc(fallback.tagline)}
        </p>

      </div>


      <div class="intro-text">

        <p>

          <strong>
            Worum geht es?
          </strong>

          <br>

          ${esc(fallback.goal)}

        </p>

      </div>

    </div>

  `;


  topics.innerHTML = `
    <div class="loading">
      Themen werden geladen …
    </div>
  `;


  grammar.innerHTML = `
    <div class="loading">
      Grammatik wird geladen …
    </div>
  `;


  /*
    Load everything together
  */

  const [
    levelResult,
    topicsResult,
    grammarResult
  ] =
    await Promise.all([

      getRows(
        "levels",
        {
          eq: {
            level: levelName
          }
        }
      ),

      getRows(
        "topics",
        {
          eq: {
            level: levelName
          },

          order:
            "sort_order"
        }
      ),

      getRows(
        "grammar_topics",
        {
          eq: {
            level: levelName
          },

          order:
            "sort_order"
        }
      )

    ]);


  /*
    Update level introduction
  */

  if (
    !levelResult.error &&
    levelResult.data &&
    levelResult.data.length
  ) {

    const level =
      levelResult.data[0];


    intro.innerHTML = `

      <div class="level-intro">

        <div>

          <span class="eyebrow">
            ${esc(level.level)}
          </span>

          <h1>
            ${esc(level.title)}
          </h1>

          <p>
            ${esc(level.tagline || "")}
          </p>

        </div>


        <div class="intro-text">

          <p>

            <strong>
              Worum geht es?
            </strong>

            <br>

            ${esc(level.goal || "")}

          </p>

        </div>

      </div>

    `;

  }


  // =================================================
  // TOPICS
  // =================================================

  if (
    topicsResult.error ||
    !topicsResult.data ||
    !topicsResult.data.length
  ) {

    topics.innerHTML = `

      <div class="empty-state">

        Noch keine Themen in Supabase.

      </div>

    `;

  } else {

    const visibleTopics =
      topicsResult.data.filter(
        topic =>
          topic.published !== false
      );


    topics.innerHTML =
      visibleTopics
        .map(
          topic => `

            <article
              class="topic-card"
            >

              <div class="topic-icon">
                ${esc(
                  topic.icon ||
                  "📘"
                )}
              </div>


              <span class="eyebrow">
                ${esc(
                  topic.category ||
                  "Thema"
                )}
              </span>


              <h3>
                ${esc(topic.title)}
              </h3>


              <p class="summary">
                ${esc(
                  topic.summary ||
                  ""
                )}
              </p>


              <button
                class="button secondary"
                data-topic-id="${esc(
                  topic.id
                )}"
              >
                Ansehen
              </button>

            </article>

          `
        )
        .join("");


    /*
      Topic buttons
    */

    topics
      .querySelectorAll(
        "[data-topic-id]"
      )
      .forEach(
        button => {

          button.onclick =
            async function () {

              const result =
                await getRows(
                  "topics",
                  {
                    eq: {
                      id:
                        button.dataset
                          .topicId
                    }
                  }
                );


              if (
                !result.error &&
                result.data &&
                result.data.length
              ) {

                openModal(
                  result.data[0].title,

                  renderDetail(
                    result.data[0]
                  )
                );

              }

            };

        }
      );

  }


  // =================================================
  // GRAMMAR
  // =================================================

  if (
    grammarResult.error ||
    !grammarResult.data ||
    !grammarResult.data.length
  ) {

    grammar.innerHTML = `

      <div class="empty-state">

        Noch keine Grammatikthemen in Supabase.

      </div>

    `;

  } else {

    const visibleGrammar =
      grammarResult.data.filter(
        item =>
          item.published !== false
      );


    grammar.innerHTML =
      visibleGrammar
        .map(
          (grammar, index) => `

            <article
              class="grammar-item"
            >

              <div class="grammar-number">

                ${String(
                  index + 1
                ).padStart(
                  2,
                  "0"
                )}

              </div>


              <div>

                <h3>
                  ${esc(
                    grammar.title
                  )}
                </h3>


                <p>
                  ${esc(
                    grammar.short_explanation ||
                    ""
                  )}
                </p>

              </div>


              <button
                class="button secondary open-detail"
                data-grammar-id="${esc(
                  grammar.id
                )}"
              >
                Ansehen
              </button>

            </article>

          `
        )
        .join("");


    /*
      Grammar buttons
    */

    grammar
      .querySelectorAll(
        "[data-grammar-id]"
      )
      .forEach(
        button => {

          button.onclick =
            async function () {

              const result =
                await getRows(
                  "grammar_topics",
                  {
                    eq: {
                      id:
                        button.dataset
                          .grammarId
                    }
                  }
                );


              if (
                !result.error &&
                result.data &&
                result.data.length
              ) {

                openModal(
                  result.data[0].title,

                  renderDetail(
                    result.data[0]
                  )
                );

              }

            };

        }
      );

  }

}


// =====================================================
// 12. DETAIL CONTENT
// =====================================================

function renderDetail(
  row
) {

  const keyPoints =
    listify(
      row.key_points
    );


  const sentencePatterns =
    listify(
      row.sentence_patterns
    );


  const examples =
    listify(
      row.examples
    );


  return `

    ${
      row.explanation

      ? `

        <div class="detail-block">

          <h3>
            📖 Einfach erklärt
          </h3>

          <div class="detail-box">
            ${esc(
              row.explanation
            )}
          </div>

        </div>

      `

      : ""
    }


    ${
      keyPoints.length

      ? `

        <div class="detail-block">

          <h3>
            ⭐ Wichtig
          </h3>

          <div class="detail-box">

            <ul class="example-list">

              ${keyPoints
                .map(
                  point =>
                    `<li>${esc(point)}</li>`
                )
                .join("")
              }

            </ul>

          </div>

        </div>

      `

      : ""
    }


    ${
      sentencePatterns.length

      ? `

        <div class="detail-block">

          <h3>
            💬 Satzmuster
          </h3>

          <div class="detail-box">

            <ul class="example-list">

              ${sentencePatterns
                .map(
                  sentence =>
                    `<li>${esc(sentence)}</li>`
                )
                .join("")
              }

            </ul>

          </div>

        </div>

      `

      : ""
    }


    ${
      examples.length

      ? `

        <div class="detail-block">

          <h3>
            💡 Beispiele
          </h3>

          <div class="detail-box">

            <ul class="example-list">

              ${examples
                .map(
                  example =>
                    `<li>${esc(example)}</li>`
                )
                .join("")
              }

            </ul>

          </div>

        </div>

      `

      : ""
    }


    ${
      row.merke

      ? `

        <div class="detail-block">

          <h3>
            🧠 Merke
          </h3>

          <div class="detail-box">

            <strong>
              ${esc(row.merke)}
            </strong>

          </div>

        </div>

      `

      : ""
    }


    ${
      row.image_url

      ? `

        <div class="detail-block">

          <img
            src="${esc(row.image_url)}"
            alt=""
            style="
              width:100%;
              border-radius:18px;
            "
          >

        </div>

      `

      : ""
    }

  `;

}


// =====================================================
// 13. MODAL
// =====================================================

function openModal(
  title,
  body
) {

  let modal =
    document.getElementById(
      "detailModal"
    );


  /*
    Create modal only once
  */

  if (!modal) {

    document.body.insertAdjacentHTML(
      "beforeend",

      `

        <div
          class="detail-modal"
          id="detailModal"
        >

          <div class="modal-card">

            <button
              class="modal-close"
              id="modalClose"
              aria-label="Schließen"
            >
              ✕
            </button>


            <div
              id="modalContent"
            ></div>

          </div>

        </div>

      `

    );


    modal =
      document.getElementById(
        "detailModal"
      );


    const closeButton =
      document.getElementById(
        "modalClose"
      );


    if (closeButton) {

      closeButton.onclick =
        function () {

          modal.classList.remove(
            "open"
          );

        };

    }


    modal.onclick =
      function (event) {

        if (
          event.target === modal
        ) {

          modal.classList.remove(
            "open"
          );

        }

      };

  }


  const content =
    document.getElementById(
      "modalContent"
    );


  content.innerHTML = `

    <span class="eyebrow">
      REVISION
    </span>

    <h2>
      ${esc(title)}
    </h2>

    ${body}

  `;


  modal.classList.add(
    "open"
  );

}


// =====================================================
// 14. VOCABULARY PAGE
// =====================================================

async function renderVocabulary() {

  const grid =
    document.getElementById(
      "vocab-grid"
    );


  const filterHost =
    document.getElementById(
      "vocab-filters"
    );


  if (
    !grid ||
    !filterHost
  ) {
    return;
  }


  const result =
    await getRows(
      "vocabulary",
      {
        order:
          "sort_order"
      }
    );


  if (
    result.error ||
    !result.data ||
    !result.data.length
  ) {

    grid.innerHTML = `

      <div class="empty-state">

        Noch kein Wortschatz in Supabase.

      </div>

    `;

    return;

  }


  const rows =
    result.data.filter(
      row =>
        row.published !== false
    );


  let selectedLevel =
    "Alle";


  let selectedCategory =
    "Alle";


  const levels = [

    "Alle",

    ...new Set(
      rows
        .map(
          row =>
            row.level
        )
        .filter(Boolean)
    )

  ];


  const categories = [

    "Alle",

    ...new Set(
      rows
        .map(
          row =>
            row.category
        )
        .filter(Boolean)
    )

  ];


  function draw() {

    filterHost.innerHTML = "";


    const levelFilters =
      document.createElement(
        "div"
      );


    levelFilters.className =
      "filters";


    createFilterButtons(
      levelFilters,

      levels,

      selectedLevel,

      function (value) {

        selectedLevel =
          value;

        draw();

      }
    );


    const categoryFilters =
      document.createElement(
        "div"
      );


    categoryFilters.className =
      "filters";


    createFilterButtons(
      categoryFilters,

      categories,

      selectedCategory,

      function (value) {

        selectedCategory =
          value;

        draw();

      }
    );


    filterHost.append(
      levelFilters,
      categoryFilters
    );


    const filtered =
      rows.filter(
        row =>

          (
            selectedLevel === "Alle" ||
            row.level === selectedLevel
          )

          &&

          (
            selectedCategory === "Alle" ||
            row.category === selectedCategory
          )

      );


    grid.innerHTML =
      filtered
        .map(
          vocabulary => `

            <article
              class="vocab-card"
            >

              <span class="eyebrow">

                ${esc(
                  vocabulary.level
                )}

                ·

                ${esc(
                  vocabulary.category
                )}

              </span>


              <div class="vocab-word">

                ${esc(
                  vocabulary.article
                    ? vocabulary.article + " "
                    : ""
                )}

                ${esc(
                  vocabulary.word
                )}

              </div>


              <div class="vocab-meta">

                ${
                  vocabulary.plural
                    ? "Plural: " +
                      esc(
                        vocabulary.plural
                      )
                    : ""
                }


                ${
                  vocabulary.meaning
                    ? " · " +
                      esc(
                        vocabulary.meaning
                      )
                    : ""
                }

              </div>


              <div class="vocab-example">

                ${esc(
                  vocabulary.example ||
                  ""
                )}

              </div>

            </article>

          `
        )
        .join("");


    if (!filtered.length) {

      grid.innerHTML = `

        <div class="empty-state">

          Keine Wörter für diese Auswahl.

        </div>

      `;

    }

  }


  draw();

}


// =====================================================
// 15. FILTER BUTTONS
// =====================================================

function createFilterButtons(
  host,
  values,
  current,
  onChange
) {

  host.innerHTML =
    values
      .map(
        value => `

          <button
            class="filter-btn ${
              value === current
                ? "active"
                : ""
            }"
            data-filter="${esc(
              value
            )}"
          >

            ${esc(value)}

          </button>

        `
      )
      .join("");


  host
    .querySelectorAll(
      "[data-filter]"
    )
    .forEach(
      button => {

        button.onclick =
          function () {

            onChange(
              button.dataset.filter
            );

          };

      }
    );

}


// =====================================================
// 16. GRAMMAR PAGE
// =====================================================

async function renderGrammar() {

  const grid =
    document.getElementById(
      "grammar-grid"
    );


  const filterHost =
    document.getElementById(
      "grammar-filters"
    );


  if (
    !grid ||
    !filterHost
  ) {
    return;
  }


  const result =
    await getRows(
      "grammar_topics",
      {
        order:
          "sort_order"
      }
    );


  if (
    result.error ||
    !result.data ||
    !result.data.length
  ) {

    grid.innerHTML = `

      <div class="empty-state">

        Noch keine Grammatikthemen in Supabase.

      </div>

    `;

    return;

  }


  const rows =
    result.data.filter(
      row =>
        row.published !== false
    );


  let selectedLevel =
    "Alle";


  const levels = [

    "Alle",

    ...new Set(
      rows
        .map(
          row =>
            row.level
        )
        .filter(Boolean)
    )

  ];


  function draw() {

    createFilterButtons(

      filterHost,

      levels,

      selectedLevel,

      function (value) {

        selectedLevel =
          value;

        draw();

      }

    );


    const filtered =
      rows.filter(
        row =>

          selectedLevel === "Alle" ||

          row.level ===
            selectedLevel

      );


    grid.innerHTML =
      filtered
        .map(
          grammar => `

            <article
              class="grammar-card"
            >

              <span class="level-badge">

                ${esc(
                  grammar.level
                )}

              </span>


              <h3>

                ${esc(
                  grammar.title
                )}

              </h3>


              <p>

                ${esc(
                  grammar.short_explanation ||
                  ""
                )}

              </p>


              <div class="rule">

                ${esc(
                  grammar.rule_preview ||
                  ""
                )}

              </div>


              <br>


              <button
                class="button secondary"
                data-grammar-open="${esc(
                  grammar.id
                )}"
              >

                Ansehen

              </button>

            </article>

          `
        )
        .join("");


    grid
      .querySelectorAll(
        "[data-grammar-open]"
      )
      .forEach(
        button => {

          button.onclick =
            async function () {

              const result =
                await getRows(
                  "grammar_topics",
                  {
                    eq: {
                      id:
                        button.dataset
                          .grammarOpen
                    }
                  }
                );


              if (
                !result.error &&
                result.data &&
                result.data.length
              ) {

                openModal(
                  result.data[0].title,

                  renderDetail(
                    result.data[0]
                  )
                );

              }

            };

        }
      );

  }


  draw();

}


// =====================================================
// 17. ESC CLOSES MODAL
// =====================================================

document.addEventListener(
  "keydown",

  function (event) {

    if (
      event.key === "Escape"
    ) {

      const modal =
        document.querySelector(
          ".detail-modal.open"
        );


      if (modal) {

        modal.classList.remove(
          "open"
        );

      }

    }

  }

);


// =====================================================
// 18. START WEBSITE
// =====================================================

(async function init() {

  renderHeader();

  renderFooter();


  /*
    Connect to Supabase
  */

  try {

    await connectSupabase();

  } catch (error) {

    console.error(
      "Supabase connection failed:",
      error
    );

  }


  /*
    Decide what the current
    HTML page needs.
  */

  if (
    page === "home"
  ) {

    await renderLevelCards(
      "home-levels"
    );

  }


  else if (
    page === "learn"
  ) {

    await renderLevelCards(
      "all-levels"
    );

  }


  else if (
    page === "level"
  ) {

    await renderLevelPage(
      document.body.dataset.level
    );

  }


  else if (
    page === "vocabulary"
  ) {

    await renderVocabulary();

  }


  else if (
    page === "grammar"
  ) {

    await renderGrammar();

  }

})();
